<section class="container">
    <div class="row">
        <div class=" col-md-4 col-md-offset-4">
            <?= isset($error) ? '<div class="alert alert-danger" role="alert">' . $error . '!</div>' : ''; ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Login</strong>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" action="/main/login">
                        <div class="panel-body">
                            <div class="form-group input-group">
                                    <span class="input-group-addon"><span
                                            class="glyphicon glyphicon-log-in"></span></span>
                                <input class="form-control" type="text" name="login" placeholder="Login" required autofocus>
                            </div>
                            <div class="form-group input-group">
                                    <span class="input-group-addon"><span
                                            class="glyphicon glyphicon-lock"></span></span>
                                <input class="form-control" type="password" name="password" placeholder="Password" required>
                            </div>
                            <input type="hidden" name="_csrf" value="<?= isset($_csrf) ? $_csrf : '' ?>">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </form>
                    <div class="forgot_password">
                        <a href="">Forgot your password?</a>
                    </div>
                </div>
                <div class="panel-footer">
                    <a class="btn btn-success btn-block" href="/main/signup" role="button">Sign up</a>
                </div>
            </div>
        </div>
    </div>
    <!-- end form -->
</section>