<section class="container">
    <div class="row">
        <div class=" col-md-4 col-md-offset-4">
            <?= isset($error) ? '<div class="alert alert-danger" role="alert">' . $error . '!</div>' : '' ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Sign up</strong>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" action="/main/signup">
                        <div class="panel-body">
                            <div class="form-group input-group">
                                    <span class="input-group-addon"><span
                                            class="glyphicon glyphicon-log-in"></span></span>
                                <input class="form-control" type="text" name="login" placeholder="Login" pattern="^.{6,20}$"
                                       title="Login must be from 6 to 20 signs" required autofocus>
                            </div>
                            <div class="form-group input-group">
                                    <span class="input-group-addon"><span
                                            class="glyphicon glyphicon-lock"></span></span>
                                <input class="form-control" type="password" name="password" placeholder="Password" pattern="^(\d|\w|-|_){3,20}$"
                                       title="Password must be from 3 to 20 signs" required>
                            </div>
                            <div class="form-group input-group">
                                    <span class="input-group-addon"><span
                                            class="glyphicon glyphicon-lock"></span></span>
                                <input class="form-control" type="password" name="repassword" placeholder="Repassword" pattern="^(\d|\w|-|_){3,20}$"
                                       title="Password must be from 3 to 20 signs" required>
                            </div>
                            <div class="form-group input-group">
                                    <span class="input-group-addon"><span
                                            class="glyphicon glyphicon-envelope"></span></span>
                                <input class="form-control" type="email" name="email" placeholder="Email" maxlength="50" required>
                                <input type="hidden" name="_csrf" value="<?= isset($_csrf) ? $_csrf : '' ?>">
                            </div>

                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Sign up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- end form -->
</section>