<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Chat room</title>

    <link rel="stylesheet" href="/components/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/styles/style.css">
</head>

<body>
<!--TOP MENU-->
<header class="navbar_margin">
    <nav class="navbar navbar-default navbar-fixed-top top-menu-black">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed burger-button" data-toggle="collapse"
                                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>

                            </button>
                            <a class="navbar-brand logo" href="/main/index"><b>Chat</b></a>
                        </div>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right header-right">
                                <li class="header_text_al">
                                    <a href="/main/signup">
                                        Signup <span class="glyphicon glyphicon-ok"></span>
                                    </a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" id="pad_null" data-toggle="dropdown" role="button" aria-haspopup="true"
                                       aria-expanded="false">
                                        <?= isset($_SESSION['login']) ? $_SESSION['login'] : '' ?>
                                        <span class="glyphicon glyphicon-user"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <?= isset($_SESSION['login']) ? '<a href="/main/logout">Log out</a>' : '<a href="/main/login">Log in</a>' ?>
                                        </li>
                                    </ul>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
<!--END TOP MENU-->

<?= $this->content; ?>


<!--FOOTER-->
<footer id="footer">
    <div class="container-fluid">
        <div class="navbar navbar-default">
            <div class="container col-md-12 text-center">
                <div class="row">
                    <p class="navbar-center copyright-mar">Copyright &copy; <?= date('Y') ?> - Free online chat
                        <a href="/main/index">Chat.com</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--END FOOTER-->

<script src="/components/jquery/jquery.min.js"></script>
<script src="/components/bootstrap/js/bootstrap.min.js"></script>

</body>
</html>